export const CONTENT_STATES = ["Idea","Brief","Draft","Review","Approved","Scheduled","Published","Measured","Updated","Archived"] as const;
export type ContentState = typeof CONTENT_STATES[number];
export type MarketingData = { source:"d1"|"demonstration"; database:"connected"|"connected_empty"|"unavailable"|"authorization_required"; asOf:string; activation:string; metrics:{pipeline:number; awaitingApproval:number; activeCampaigns:number; approvedClaims:number; permissionReady:number; inquiries:number; influencedPipeline:number|null; claimDefects:number}; assets:Array<{id:string;title:string;status:ContentState;audience:string;channel:string;owner:string;brandVersion:string;claims:number;permission:string;window:string;campaign:string}>; campaigns:Array<{id:string;name:string;status:string;objective:string;assets:number;inquiries:number;attribution:string;stopCriteria:string}>; claims:Array<{id:string;claim:string;status:string;evidence:string;expires:string}>; calendar:Array<{date:string;asset:string;stage:string;channel:string}>; alerts:Array<{type:string;message:string;owner:string}> };

export function mayTransitionContent(from:ContentState,to:ContentState,input:{humanApproval?:boolean;claimsApproved?:boolean;permissionsActive?:boolean;publicationEvidence?:boolean;measurementSource?:boolean}) {
  const next:Record<ContentState,ContentState[]>={Idea:["Brief"],Brief:["Draft"],Draft:["Review"],Review:["Approved","Draft"],Approved:["Scheduled","Updated","Archived"],Scheduled:["Published","Updated","Archived"],Published:["Measured","Updated","Archived"],Measured:["Updated","Archived"],Updated:["Review","Archived"],Archived:[]};
  if(!next[from].includes(to)) return false;
  if(to==="Approved"&&!input.humanApproval) return false;
  if(["Approved","Scheduled","Published"].includes(to)&&(!input.claimsApproved||!input.permissionsActive)) return false;
  if(to==="Published"&&!input.publicationEvidence) return false;
  if(to==="Measured"&&!input.measurementSource) return false;
  return true;
}
export function claimGate(input:{status:string;evidence:string;expired?:boolean;scopeMatches:boolean}){return input.status==="Approved"&&Boolean(input.evidence.trim())&&!input.expired&&input.scopeMatches;}
export function permissionGate(input:{classification:string;clientIdentified:boolean;name?:boolean;logo?:boolean;images?:boolean;quote?:boolean;results?:boolean;expired?:boolean;withdrawn?:boolean}){if(input.expired||input.withdrawn)return {publishable:false,mode:"Blocked"};const required=input.clientIdentified&&input.classification!=="Internal";return required&&![input.name,input.logo,input.images,input.quote,input.results].every(Boolean)?{publishable:false,mode:"Anonymized internal draft"}:{publishable:true,mode:"Permitted"};}
export function inspectSource(text:string,classification:string){const injection=/ignore (?:all|previous)|system message|publish now|reveal (?:secret|confidential)|contact (?:the )?client/i.test(text);return {trustedInstructions:false,quarantine:injection,classification,action:injection?"Preserve as untrusted evidence; do not execute embedded instructions.":"Use as evidence only after owner, permission, and claim review."};}
export function validateLeadHandoff(input:Record<string,string>){const required=["source","campaign","content","consentStatus","organization","statedNeed","timestamp","attribution","nextAction","correlationId"];return {valid:required.every(k=>Boolean(input[k]?.trim())),missing:required.filter(k=>!input[k]?.trim()),recipient:"AGT-002"};}

export const demonstrationMarketingData:MarketingData={source:"demonstration",database:"connected_empty",asOf:"2026-07-21T16:00:00.000Z",activation:"Demonstration records only. No publishing, email, advertising, analytics, CRM attribution, social channel, or external lead contact is live.",metrics:{pipeline:8,awaitingApproval:3,activeCampaigns:2,approvedClaims:4,permissionReady:1,inquiries:0,influencedPipeline:null,claimDefects:1},assets:[
  {id:"CNT-2026-011",title:"The building intelligence gap",status:"Review",audience:"Facilities leaders",channel:"Article draft",owner:"AGT-011",brandVersion:"BRAND-001",claims:2,permission:"Ready",window:"Jul 28–Aug 1",campaign:"CMP-2026-003"},
  {id:"CNT-2026-012",title:"From reality capture to decisions",status:"Draft",audience:"BIM / VDC leaders",channel:"LinkedIn draft",owner:"AGT-011",brandVersion:"BRAND-001",claims:1,permission:"Internal only",window:"Not scheduled",campaign:"CMP-2026-003"},
  {id:"CNT-2026-014",title:"Portfolio operations outcome story",status:"Brief",audience:"Building owners",channel:"Case study",owner:"AGT-011",brandVersion:"BRAND-001",claims:3,permission:"Name + logo missing",window:"Blocked",campaign:"CMP-2026-004"}],
 campaigns:[{id:"CMP-2026-003",name:"Operating System for Buildings",status:"Draft",objective:"Clarify the category",assets:5,inquiries:0,attribution:"Plan only",stopCriteria:"Any claim or permission defect"},{id:"CMP-2026-004",name:"Evidence in operations",status:"Review",objective:"Support qualified discovery",assets:3,inquiries:0,attribution:"Not connected",stopCriteria:"Permission withdrawal or evidence expiry"}],
 claims:[{id:"CLM-001",claim:"Symbiont connects building reality, data, and operational decisions.",status:"Approved",evidence:"Brand positioning record",expires:"2026-10-01"},{id:"CLM-004",claim:"Portfolio teams can use governed building data to support operational decisions.",status:"Approved",evidence:"Product definition + technical review",expires:"2026-09-15"}],
 calendar:[{date:"Jul 23",asset:"CNT-2026-011",stage:"Human review",channel:"Article draft"},{date:"Jul 25",asset:"CNT-2026-012",stage:"Claim review",channel:"Social draft"},{date:"Jul 29",asset:"CNT-2026-014",stage:"Permission review",channel:"Case study"}],
 alerts:[{type:"Permission",message:"CNT-2026-014 cannot identify the client until name and logo permissions are recorded.",owner:"Marketing owner"},{type:"Claim",message:"One draft contains an outcome statement without linked evidence.",owner:"AGT-011"},{type:"Freshness",message:"CLM-004 enters its 45-day evidence review window next month.",owner:"Claim owner"}]};

