export const lifecycle = ["Idea","Discovery","Validation","Pilot","Active","Scaling","Sunset","Retired"] as const;
export type LifecycleStage = typeof lifecycle[number];
export const qualificationDimensions = ["problemSeverity","buyerClarity","frequency","strategicFit","repeatability","technicalFeasibility","deliveryFeasibility","dataAvailability","qualityRisk","securityRisk","marginPotential","recurringRevenuePotential","differentiation","evidenceStrength"] as const;
export type QualificationScores = Partial<Record<typeof qualificationDimensions[number],number>>;

export function qualifyConcept(scores:QualificationScores){
  const missing=qualificationDimensions.filter(key=>scores[key]==null);
  const invalid=qualificationDimensions.filter(key=>scores[key]!=null&&(scores[key]!<0||scores[key]!>5));
  if(invalid.length)throw new Error(`Qualification scores must be between 0 and 5: ${invalid.join(", ")}.`);
  const score=Math.round(qualificationDimensions.reduce((sum,key)=>sum+(scores[key]??0),0)/70*100);
  const classification=missing.length||scores.evidenceStrength!<2?"Explore":score>=80?"Productize":score>=65?"Pilot":score>=48?"Validate":score>=32?"Explore":"Hold";
  return {score,classification,missing};
}

type GateEvidence={problem?:boolean;audience?:boolean;sourceEvidence?:boolean;owner?:boolean;correlationId?:boolean;qualification?:boolean;assumptions?:boolean;experiment?:boolean;baseline?:boolean;criteria?:boolean;approval?:boolean;boundedScope?:boolean;acceptance?:boolean;qualityPlan?:boolean;securityPlan?:boolean;economicsInputs?:boolean;pilotSuccess?:boolean;clientOutcome?:boolean;actualEffort?:boolean;defects?:boolean;approvedVersion?:boolean;supportModel?:boolean;approvalDecision?:boolean;adoption?:boolean;deliveryVariation?:boolean;capacity?:boolean;recurringRevenue?:boolean;margin?:boolean;multipleEvidencePoints?:boolean;impactAnalysis?:boolean;communicationPlan?:boolean;exitPath?:boolean;effectiveDate?:boolean;proposalExcluded?:boolean;archivedVersions?:boolean};
const gates:Record<LifecycleStage,(keyof GateEvidence)[]>={Idea:[],Discovery:["problem","audience","sourceEvidence","owner","correlationId"],Validation:["qualification","assumptions","experiment","baseline","criteria"],Pilot:["approval","boundedScope","acceptance","qualityPlan","securityPlan","economicsInputs"],Active:["pilotSuccess","clientOutcome","actualEffort","defects","approvedVersion","supportModel","approvalDecision"],Scaling:["adoption","deliveryVariation","capacity","recurringRevenue","margin","multipleEvidencePoints"],Sunset:["impactAnalysis","communicationPlan","exitPath","approvalDecision"],Retired:["effectiveDate","proposalExcluded","archivedVersions","approvalDecision"]};
export function assertLifecycleTransition(from:LifecycleStage,to:LifecycleStage,evidence:GateEvidence){
  const fromIndex=lifecycle.indexOf(from),toIndex=lifecycle.indexOf(to);
  if(toIndex!==fromIndex+1)throw new Error(`Lifecycle transitions must advance one stage at a time (${from} → ${to} is not allowed).`);
  const missing=gates[to].filter(key=>!evidence[key]);
  if(missing.length)throw new Error(`Lifecycle promotion to ${to} requires: ${missing.join(", ")}.`);
  return true;
}
export function assertDraftAuthority(action:string){if(["approve pricing","commit client","publish claim","allocate capacity","authorize investment","certify"].some(item=>action.toLowerCase().includes(item)))throw new Error("AGT-010 is L1 Draft: pricing, client commitments, publication, capacity, investment, and certification require authorized approval.");return true;}
export function assertProposalVersion(version:{approvalStatus:string;proposalEligible:boolean;supersededAt?:string|null},currentVersionId:string,versionId:string){if(versionId!==currentVersionId||version.approvalStatus!=="Approved"||!version.proposalEligible||version.supersededAt)throw new Error("Only the approved, current, non-superseded product version may be used in a proposal.");return true;}
export function assertEconomicsInputs(input:Record<string,number|null|undefined>){const required=["deliveryCost","softwareCost","supportCost","implementationCost","contingencyCost"] as const;const missing=required.filter(key=>input[key]==null);if(missing.length)throw new Error(`Product economics requires explicit inputs: ${missing.join(", ")}.`);return true;}
export function draftProductClaim(claim:string,evidence?:{source?:string;baseline?:string;method?:string;observed?:boolean}){if(!evidence?.source||!evidence.baseline||!evidence.method||!evidence.observed)throw new Error(`Unsupported product claim refused: "${claim}". Record it as a hypothesis with a baseline and validation plan.`);return `${claim} · supported by ${evidence.source}`;}

export type ProductPortfolioData={source:"d1"|"demonstration";database:"connected"|"connected_empty"|"unavailable"|"authorization_required";asOf:string;activation:string;products:Array<{id:string;name:string;stage:LifecycleStage;health:string;version:string;pilot:string;recurring:string;margin:number|null;adoption:number|null;variation:number|null;quality:number;assumptions:number;feedback:string;modules:number;retirementCandidate:boolean;proposalEligible:boolean;isDemonstration:boolean}>;roadmap:Array<{id:string;productId:string;title:string;lane:string;status:string;targetDate:string|null}>};
export const demonstrationProductData:ProductPortfolioData={source:"demonstration",database:"connected_empty",asOf:new Date().toISOString(),activation:"Clearly labeled demonstration portfolio. Activate the AGT-010 migration and authenticated evidence to report live product performance.",products:[
  {id:"PROD-DEMO-001",name:"Existing-Conditions Intelligence Foundation — DEMO",stage:"Pilot",health:"Amber",version:"0.3.0",pilot:"Bounded pilot · approval recorded",recurring:"Medium",margin:38,adoption:62,variation:18,quality:2,assumptions:3,feedback:"Clients value faster validation; handoff effort remains unproven.",modules:3,retirementCandidate:false,proposalEligible:false,isDemonstration:true},
  {id:"PROD-DEMO-002",name:"Building Data Operations — DEMO",stage:"Validation",health:"Unknown",version:"0.2.0",pilot:"Baseline design in review",recurring:"High",margin:null,adoption:null,variation:null,quality:0,assumptions:5,feedback:"Recurring request pattern; economics evidence incomplete.",modules:4,retirementCandidate:false,proposalEligible:false,isDemonstration:true},
  {id:"PROD-DEMO-003",name:"Legacy Model Refresh — DEMO",stage:"Sunset",health:"Red",version:"1.4.0",pilot:"Not applicable",recurring:"Low",margin:12,adoption:14,variation:41,quality:6,assumptions:1,feedback:"High variation and low adoption; successor analysis required.",modules:1,retirementCandidate:true,proposalEligible:false,isDemonstration:true}
],roadmap:[{id:"RDM-DEMO-001",productId:"PROD-DEMO-001",title:"Close pilot effort and defect baseline",lane:"Committed",status:"In progress",targetDate:"2026-08-15"},{id:"RDM-DEMO-002",productId:"PROD-DEMO-002",title:"Validate recurring support model",lane:"Candidate",status:"Candidate",targetDate:"2026-09-01"}]};
