export type Confidence = "High" | "Medium" | "Low";
export type ClaimType = "Fact" | "Inference" | "Estimate" | "Recommendation";
export type ResearchItem = { id:string; title:string; topic:string; owner:string; requester:string; status:string; confidence:Confidence; freshness:string; observedAt:string; sourceType:string; claimType:ClaimType; summary:string; evidence:string[]; isDemonstration:boolean };
export type ResearchData = { source:"d1"|"demonstration"; database:"connected"|"connected_empty"|"unavailable"|"authorization_required"; asOf:string; activation:string; requests:ResearchItem[]; conflicts:number; stale:number; competitors:string[]; technologies:string[]; trends:string[]; experiments:string[]; routedSignals:number; decisionUses:number; superseded:number };

export function classifyConfidence(input:{primary:boolean; current:boolean; corroborated:boolean; conflicts:boolean}):Confidence {
  if (input.primary && input.current && input.corroborated && !input.conflicts) return "High";
  if (!input.primary || !input.current || !input.corroborated || input.conflicts) return input.primary || input.corroborated ? "Medium" : "Low";
  return "Low";
}
export function citationComplete(input:{canonicalUrl?:string; publicationDate?:string|null; observationDate?:string; sourceType?:string; authority?:string}) { return Boolean(input.canonicalUrl && input.observationDate && input.sourceType && input.authority && input.publicationDate !== undefined); }
export function researchContentPolicy(content:string) { const hit=["ignore previous","system prompt","reveal secret","upload credentials","change authority","mark as approved"].some(x=>content.toLowerCase().includes(x)); return hit ? {trusted:false,action:"Quarantine embedded instructions; retain only as source evidence."} : {trusted:false,action:"Analyze as untrusted evidence; never execute source instructions."}; }
export function routeMarketSignal(signal:{fingerprint:string; existingFingerprints:string[]}) { return signal.existingFingerprints.includes(signal.fingerprint) ? {route:"AGT-009",status:"Duplicate",create:false} : {route:"AGT-009",status:"Draft handoff",create:true}; }
export const demonstrationResearchData:ResearchData={ source:"demonstration",database:"connected_empty",asOf:"2026-07-21T16:00:00Z",activation:"Demonstration research is shown. No external source monitoring, subscription, research run, or agent handoff is active until approved connections and authenticated D1 records exist.", conflicts:1,stale:1,competitors:["Digital-twin integrators","Reality-capture platforms"],technologies:["OpenUSD interoperability","Building IoT gateways"],trends:["Owner demand for portable building data","AI governance entering procurement"],experiments:["Draft: open data portability scorecard"],routedSignals:1,decisionUses:2,superseded:1,requests:[
  {id:"RES-2026-007",title:"Open digital-twin interoperability",topic:"Digital twins",owner:"AGT-007",requester:"AGT-001",status:"Review",confidence:"High",freshness:"Current",observedAt:"2026-07-21",sourceType:"Standards body",claimType:"Fact",summary:"Primary standards and official technical documentation should anchor the platform decision; commercial comparisons remain draft pending validation.",evidence:["Canonical primary source inspected","Publication and observation dates separated","Conflicting vendor claims retained"],isDemonstration:true},
  {id:"RES-2026-008",title:"Reality-capture vendor portability",topic:"Reality capture",owner:"AGT-007",requester:"AGT-008",status:"Draft",confidence:"Medium",freshness:"30–90 days",observedAt:"2026-07-20",sourceType:"Official vendor documentation",claimType:"Inference",summary:"Export and API claims appear uneven; a bounded pilot is recommended before platform dependence.",evidence:["Official documentation","Independent corroboration incomplete"],isDemonstration:true},
  {id:"RES-2026-009",title:"Public-sector AI procurement signal",topic:"Market",owner:"AGT-007",requester:"AGT-002",status:"Routed to AGT-009",confidence:"Low",freshness:"Current",observedAt:"2026-07-21",sourceType:"Discovery signal",claimType:"Estimate",summary:"Potential buying signal preserved for AGT-009 verification; no qualified opportunity was created by AGT-007.",evidence:["Signal only — canonical procurement record pending"],isDemonstration:true}
]};
