import { NextResponse } from "next/server";
import { desc } from "drizzle-orm";
import { getDb } from "@/db";
import { financialSnapshots, financialExceptions } from "@/db/schema";
import { isAuthorized } from "@/lib/auth";
import { demonstrationFinanceData } from "@/lib/finance";
export const dynamic="force-dynamic";
export async function GET(request:Request){try{const db=await getDb();if(!isAuthorized(request))return NextResponse.json({...demonstrationFinanceData,database:"authorization_required",activation:"Authorization is required for confidential finance evidence. Sanitized demonstration data is shown; no restricted finance records are returned."});const snapshots=await db.select().from(financialSnapshots).orderBy(desc(financialSnapshots.refreshedAt)).limit(100);if(!snapshots.length)return NextResponse.json({...demonstrationFinanceData,database:"connected_empty",activation:"D1 is connected but has no approved operational-finance snapshots. Demonstration data remains clearly labeled."});const exceptions=await db.select().from(financialExceptions).orderBy(desc(financialExceptions.createdAt)).limit(100);return NextResponse.json({...demonstrationFinanceData,source:"d1",database:"connected",asOf:new Date().toISOString(),activation:"Authenticated operational-finance metadata from shared D1. The approved accounting platform remains authoritative.",metrics:snapshots.map(row=>({name:row.metricName,definition:row.definition,value:row.value,unit:row.unit,period:row.period,currency:row.currency,category:row.category,sourceSystem:row.sourceSystem,sourceRecord:row.sourceRecord,refreshedAt:row.refreshedAt,owner:row.owner,calculation:row.calculationMethod,assumptions:JSON.parse(row.assumptionsJson),confidence:row.confidence,reconciliationStatus:row.reconciliationStatus,authoritativeVariance:row.authoritativeVariance})),exceptions:exceptions.map(row=>({id:row.id,severity:row.severity,title:row.title,owner:row.owner,requiredAction:row.requiredAction,source:row.sourceRecord})),lastReconciliation:snapshots.find(row=>row.reconciliationStatus==="Reconciled")?.refreshedAt??null});}catch{return NextResponse.json({...demonstrationFinanceData,database:"unavailable",activation:"The AGT-006 D1 migration is not active or finance data is unavailable. Read-only demonstration data is shown."});}}
export async function POST(){return NextResponse.json({error:"AGT-006 has L1 Draft authority. Finance mutations, invoices, payments, accounting entries, and commitments require authenticated approval workflows and audit evidence."},{status:405,headers:{Allow:"GET"}});}
