CREATE TABLE `citations` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`claim_id` text NOT NULL,
	`canonical_url` text NOT NULL,
	`locator` text,
	`quotation` text,
	`citation_complete` integer DEFAULT false NOT NULL,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`claim_id`) REFERENCES `evidence_claims`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
INSERT OR IGNORE INTO `agents` (`id`,`name`,`mission`,`authority_level`,`parent_agent_id`,`status`,`version`) VALUES ('AGT-007','Research','Produce decision-ready, source-backed market, competitor, standards, and technology intelligence.','L1','AGT-001','Draft','0.1');
--> statement-breakpoint
CREATE TABLE `competitor_profiles` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`company` text NOT NULL,
	`profile_json` text NOT NULL,
	`strategic_implications` text NOT NULL,
	`last_activity_date` text,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `conflicting_evidence` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`claim_a_id` text NOT NULL,
	`claim_b_id` text NOT NULL,
	`conflict_summary` text NOT NULL,
	`resolution_status` text DEFAULT 'Open' NOT NULL,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`claim_a_id`) REFERENCES `evidence_claims`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`claim_b_id`) REFERENCES `evidence_claims`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `evidence_claims` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`claim` text NOT NULL,
	`claim_type` text NOT NULL,
	`directness` text NOT NULL,
	`corroboration_json` text DEFAULT '[]' NOT NULL,
	`limitations` text,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "evidence_claims_type_check" CHECK("evidence_claims"."claim_type" in ('Fact','Inference','Estimate','Recommendation'))
);
--> statement-breakpoint
CREATE TABLE `experiments` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`hypothesis` text NOT NULL,
	`method` text NOT NULL,
	`success_criteria` text NOT NULL,
	`result` text,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `market_signals` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`signal` text NOT NULL,
	`signal_type` text NOT NULL,
	`opportunity_fingerprint` text,
	`routed_to_agent_id` text,
	`routed_at` text,
	`route_status` text DEFAULT 'Not routed' NOT NULL,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `market_signals_fingerprint_idx` ON `market_signals` (`opportunity_fingerprint`);--> statement-breakpoint
CREATE TABLE `research_briefs` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`title` text NOT NULL,
	`executive_answer` text NOT NULL,
	`key_findings_json` text NOT NULL,
	`recommendation` text NOT NULL,
	`next_action` text NOT NULL,
	`version` text DEFAULT '0.1' NOT NULL,
	`review_date` text,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `research_decisions` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`decision_id` text NOT NULL,
	`use_summary` text NOT NULL,
	`decision_owner` text NOT NULL,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `research_findings` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`title` text NOT NULL,
	`finding` text NOT NULL,
	`implications` text NOT NULL,
	`assumptions_json` text DEFAULT '[]' NOT NULL,
	`unknowns_json` text DEFAULT '[]' NOT NULL,
	`superseded_by_id` text,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `research_projects` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`title` text NOT NULL,
	`plan_json` text NOT NULL,
	`stopping_rule` text NOT NULL,
	`expected_deliverable` text NOT NULL,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `research_questions` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`project_id` text NOT NULL,
	`question` text NOT NULL,
	`answer_status` text DEFAULT 'Open' NOT NULL,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`project_id`) REFERENCES `research_projects`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `research_requests` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`question` text NOT NULL,
	`decision_supported` text NOT NULL,
	`audience` text NOT NULL,
	`depth` text NOT NULL,
	`geography` text,
	`timeframe` text,
	`constraints_json` text DEFAULT '[]' NOT NULL,
	`deadline_at` text,
	`acceptance_criteria_json` text DEFAULT '[]' NOT NULL,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `research_requests_status_idx` ON `research_requests` (`status`,`requesting_agent_id`);--> statement-breakpoint
CREATE TABLE `research_reviews` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`reviewer` text NOT NULL,
	`review_type` text NOT NULL,
	`outcome` text NOT NULL,
	`comments` text,
	`reviewed_at` text NOT NULL,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `research_sources` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`canonical_url` text NOT NULL,
	`title` text NOT NULL,
	`publisher` text NOT NULL,
	`author` text,
	`source_type` text NOT NULL,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`geography` text,
	`applicable_period` text,
	`authority` text NOT NULL,
	`limitations` text,
	`content_hash` text,
	`access_restrictions` text,
	`classification` text DEFAULT 'Public' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `research_sources_url_observed_idx` ON `research_sources` (`canonical_url`,`observation_date`);--> statement-breakpoint
CREATE TABLE `source_observations` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`canonical_url` text NOT NULL,
	`observation_json` text NOT NULL,
	`content_hash` text,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `technology_profiles` (
	`id` text PRIMARY KEY NOT NULL,
	`research_id` text NOT NULL,
	`shared_goal_id` text NOT NULL,
	`correlation_id` text NOT NULL,
	`owner_agent_id` text NOT NULL,
	`requesting_agent_id` text NOT NULL,
	`source_id` text,
	`publication_date` text,
	`observation_date` text NOT NULL,
	`confidence` text NOT NULL,
	`freshness` text NOT NULL,
	`classification` text DEFAULT 'Internal' NOT NULL,
	`status` text DEFAULT 'Draft' NOT NULL,
	`evidence_links_json` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`technology` text NOT NULL,
	`assessment_json` text NOT NULL,
	`pilot_recommendation` text,
	`exit_risks_json` text DEFAULT '[]' NOT NULL,
	FOREIGN KEY (`shared_goal_id`) REFERENCES `shared_goals`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`owner_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`requesting_agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action
);
