UPDATE `shared_goals` SET
	`objective` = 'Continuously discover and verify NJ/NY state and local opportunities for network cabling, switching, telephone and unified communications, access control, security cameras, IT consulting, 3D scanning, reality capture, and building intelligence; match them to governed historical evidence and route qualified records to Sales Operations.',
	`success_measures_json` = '["Official-source coverage across NJ and NY state and local buyers","Priority service lanes include network cabling, switching, telephone, access control, security cameras, IT consulting, and 3D scanning","Every candidate is matched to governed historical capability evidence or labeled as a new prerogative","Every candidate is deduplicated and evidence-backed","Scores of 70 or more route to AGT-002 for review","Scores from 50 through 69 remain on a governed watchlist","No external contact, account creation, terms acceptance, bid submission, pricing, spending, or commitment by AGT-009"]',
	`updated_at` = '2026-07-21T11:40:00.000Z'
WHERE `id` = 'GOAL-2026-009';
--> statement-breakpoint
UPDATE `monitoring_queries` SET
	`query_text` = CASE `id`
		WHEN 'QRY-AGT009-NY-STATE' THEN 'Official New York State opportunities for network cabling, switching, telephone and unified communications, access control, security cameras, IT consulting, 3D scanning, reality capture, BIM, digital twins, and building data.'
		WHEN 'QRY-AGT009-NY-LOCAL' THEN 'Official New York local opportunities for network cabling, switching, telephone and unified communications, access control, security cameras, IT consulting, 3D scanning, reality capture, BIM, and facilities technology.'
		WHEN 'QRY-AGT009-NJ-STATE' THEN 'Official New Jersey State opportunities for network cabling, switching, telephone and unified communications, access control, surveillance cameras, IT consulting, 3D scanning, UAS, reality capture, and building data.'
		WHEN 'QRY-AGT009-NJ-LOCAL' THEN 'Official New Jersey local opportunities for network cabling, switching, telephone and unified communications, access control, security cameras, IT consulting, 3D scanning, reality capture, BIM, and facilities technology.'
		ELSE `query_text`
	END,
	`updated_at` = '2026-07-21T11:40:00.000Z'
WHERE `id` IN ('QRY-AGT009-NY-STATE','QRY-AGT009-NY-LOCAL','QRY-AGT009-NJ-STATE','QRY-AGT009-NJ-LOCAL');
--> statement-breakpoint
INSERT INTO `opportunities` (`id`, `issuer`, `issuer_website`, `title`, `normalized_title`, `solicitation_number`, `canonical_url`, `publication_date`, `deadline_at`, `deadline_timezone`, `location`, `geography_key`, `stated_value`, `currency`, `procurement_type`, `scope`, `public_contact_json`, `access_requirements`, `fit_rationale`, `service_fit_score`, `buyer_fit_score`, `timing_score`, `value_score`, `evidence_score`, `access_score`, `recurrence_score`, `total_score`, `confidence`, `freshness`, `risks_json`, `missing_information_json`, `next_action`, `route`, `handoff_status`, `observed_at`, `source_kind`, `is_demonstration`, `parent_opportunity_id`, `updated_at`) VALUES
	('OPP-2026-NYCOTI-85826P0003', 'New York City Office of Technology and Innovation', 'https://www.nyc.gov/content/oti/pages/', 'Unified Communications System', 'unified communications system', '85826P0003', 'https://a856-cityrecord.nyc.gov/RequestDetail/20260617041', '2026-06-25', '2026-08-04T15:00:00-04:00', 'America/New_York', 'New York City, NY', 'ny-local-nycoti', NULL, 'USD', 'RFP', 'Procurement, licensing, and implementation services, including cabling and electrical work, for Unified Communications System equipment, accessories, and network infrastructure hosted by NYC DoITT.', '{}', 'Solicitation documents are distributed through PASSPort; account access and platform terms are an owner boundary for AGT-009.', 'Direct continuity with Symbiont historical network, structured-cabling, voice, switching, implementation, and public-sector delivery evidence.', 98, 95, 95, 55, 92, 55, 90, 87, 93, 'Official City Record notice verified July 21, 2026', '["PASSPort account and terms boundary","OEM or licensing authorization may be required","Electrical scope may require a qualified delivery partner"]', '["Contract value","Complete minimum qualifications","MWBE goals","Prime versus subcontractor path"]', 'AGT-002 to review prime/subcontractor fit and authorize an owner to retrieve the full PASSPort package; no contact or commitment has been made.', 'sales_operations', 'Review — awaiting AGT-002 acceptance', '2026-07-21T11:30:00.000Z', 'Official NYC City Record notice', 0, NULL, '2026-07-21T11:40:00.000Z'),
	('OPP-2026-NYSOGS-23311', 'New York State Office of General Services', 'https://ogs.ny.gov/', 'Hourly Based Information Technology Services', 'hourly based information technology services', '23311', 'https://ogs.ny.gov/procurement/biddocuments/23311bid', '2026-01-30', '2026-08-12T13:30:00-04:00', 'America/New_York', 'New York statewide', 'ny-state-ogs', NULL, 'USD', 'RFP', 'Statewide hourly information-technology services contract supported by defined job titles, skill levels, regions, qualifications, technical submission, subcontractor, and contract-use requirements.', '{}', 'Public bid documents are available; bidder qualifications, certifications, insurance, and submission requirements require authorized owner review.', 'Strong match for Symbiont historical IT consulting, technical staffing, implementation, requirements, program-management, and government-delivery evidence.', 72, 90, 95, 65, 98, 60, 100, 83, 95, 'Official OGS bid page revised June 29 and verified July 21, 2026', '["Mandatory minimum qualifications","Staffing capacity and regional coverage","Pricing and contract terms require human approval"]', '["Eligible service categories","Bidder qualification fit","Teaming strategy","Approved rate structure"]', 'AGT-002 to review mandatory qualifications and determine prime, subcontractor, or no-bid path before the August 12 deadline.', 'sales_operations', 'Review — awaiting AGT-002 acceptance', '2026-07-21T11:35:00.000Z', 'Official NYS OGS bid page', 0, NULL, '2026-07-21T11:40:00.000Z')
ON CONFLICT(`id`) DO UPDATE SET
	`title` = excluded.`title`, `normalized_title` = excluded.`normalized_title`, `canonical_url` = excluded.`canonical_url`, `deadline_at` = excluded.`deadline_at`,
	`scope` = excluded.`scope`, `access_requirements` = excluded.`access_requirements`, `fit_rationale` = excluded.`fit_rationale`, `total_score` = excluded.`total_score`,
	`confidence` = excluded.`confidence`, `freshness` = excluded.`freshness`, `risks_json` = excluded.`risks_json`, `missing_information_json` = excluded.`missing_information_json`,
	`next_action` = excluded.`next_action`, `route` = excluded.`route`, `handoff_status` = excluded.`handoff_status`, `observed_at` = excluded.`observed_at`, `source_kind` = excluded.`source_kind`, `is_demonstration` = 0, `updated_at` = excluded.`updated_at`;
--> statement-breakpoint
UPDATE `opportunities` SET
	`title` = 'Law Enforcement Equipment and Technology: Surveillance, Cameras, ALPR, UAS, Software and Services',
	`normalized_title` = 'law enforcement equipment technology surveillance cameras alpr uas software services',
	`scope` = 'Statewide procurement covering surveillance, cameras, ALPR, unmanned aircraft systems, ancillary equipment, software, and related services; amendment 3 revises the quote-opening date.',
	`fit_rationale` = 'Potential fit for security cameras, physical-security technology, UAS capture, and related consulting, but the underlying scope and participation path require qualification.',
	`updated_at` = '2026-07-21T11:40:00.000Z'
WHERE `id` = 'OPP-2026-NJDPP-T3163';
--> statement-breakpoint
INSERT INTO `opportunity_evidence` (`id`, `opportunity_id`, `canonical_url`, `source_title`, `source_type`, `evidence_summary`, `content_hash`, `confidence`, `is_amendment`, `amendment_number`, `observed_at`) VALUES
	('EVD-NYCOTI-85826P0003-20260721', 'OPP-2026-NYCOTI-85826P0003', 'https://a856-cityrecord.nyc.gov/RequestDetail/20260617041', 'NYC City Record — 85826P0003 Unified Communications System', 'Official municipal procurement notice', 'NYC OTI published the notice June 25, 2026, with proposals due August 4 at 3:00 PM ET. The stated scope includes unified communications equipment, licensing, implementation, cabling, electrical work, and network infrastructure.', '1726eb6fac3f8c16d16c1f68ea706951eb74ead4fe5b5a53a7a9e89b994bb8b4', 93, 0, NULL, '2026-07-21T11:30:00.000Z'),
	('EVD-NYSOGS-23311-20260721', 'OPP-2026-NYSOGS-23311', 'https://ogs.ny.gov/procurement/biddocuments/23311bid', 'NYS OGS Solicitation 23311 — HBITS', 'Official state procurement page', 'NYS OGS lists Solicitation 23311 for Hourly Based Information Technology Services with a bid opening and completed response due August 12, 2026 at 1:30 PM ET. The page includes the revised solicitation, qualifications, job titles, skill levels, regions, and submission documents.', 'c2a0171a65a73db841e5ff9c38889b7f377d4d1c6a8cde489f09e82cdd242d80', 95, 0, NULL, '2026-07-21T11:35:00.000Z')
ON CONFLICT(`opportunity_id`, `content_hash`) DO NOTHING;
--> statement-breakpoint
INSERT INTO `knowledge_assets` (`id`, `title`, `description`, `business_area`, `asset_type`, `owner`, `author`, `reviewer`, `approver`, `lifecycle_status`, `classification`, `current_version`, `effective_date`, `review_date`, `source_system`, `canonical_location`, `source_evidence`, `content_hash`, `related_project_id`, `related_agent_id`, `retention_rule`, `tags_json`, `synonyms_json`, `is_authoritative`, `is_demonstration`, `updated_at`) VALUES
	('SYM-ARC-RES-101', 'Historical capability — network infrastructure and LAN', 'Sanitized aggregate evidence for legacy LAN, network-infrastructure, implementation, drawing, and project-control work.', 'Archive', 'RES', 'AGT-005', 'AGT-005', 'Authorized executive', NULL, 'Review', 'Internal', '0.1', NULL, '2026-07-27', 'Restricted legacy archive aggregate index', 'local-vault://capabilities/network-lan', '446 indexed text hits; full files require local archive authorization and qualification.', 'capability-network-lan-446-20260721', NULL, 'AGT-009', 'Preserve until an approved retention rule exists.', '["network","LAN","infrastructure","historical capability"]', '["ethernet","network implementation","network design"]', 0, 0, '2026-07-21T11:40:00.000Z'),
	('SYM-ARC-RES-102', 'Historical capability — structured cabling and fiber', 'Sanitized aggregate evidence for structured cabling, copper, fiber, installation, testing, materials, changes, and closeout.', 'Archive', 'RES', 'AGT-005', 'AGT-005', 'Authorized executive', NULL, 'Review', 'Internal', '0.1', NULL, '2026-07-27', 'Restricted legacy archive aggregate index', 'local-vault://capabilities/cabling-fiber', '406 indexed text hits; full files require local archive authorization and qualification.', 'capability-cabling-fiber-406-20260721', NULL, 'AGT-009', 'Preserve until an approved retention rule exists.', '["structured cabling","fiber","copper","historical capability"]', '["cable plant","voice data cabling","CAT6"]', 0, 0, '2026-07-21T11:40:00.000Z'),
	('SYM-ARC-RES-103', 'Historical capability — telephone and voice systems', 'Sanitized aggregate evidence for telephone, voice/data, VoIP, carrier, and communications-system work.', 'Archive', 'RES', 'AGT-005', 'AGT-005', 'Authorized executive', NULL, 'Review', 'Internal', '0.1', NULL, '2026-07-27', 'Restricted legacy archive aggregate index', 'local-vault://capabilities/voice-telephone', '296 indexed text hits; full files require local archive authorization and qualification.', 'capability-voice-telephone-296-20260721', NULL, 'AGT-009', 'Preserve until an approved retention rule exists.', '["telephone","voice","VoIP","historical capability"]', '["telephony","unified communications","carrier"]', 0, 0, '2026-07-21T11:40:00.000Z'),
	('SYM-ARC-RES-104', 'Historical capability — switching and network equipment', 'Sanitized aggregate evidence for switching, network equipment, telecommunications peripherals, and implementation planning.', 'Archive', 'RES', 'AGT-005', 'AGT-005', 'Authorized executive', NULL, 'Review', 'Internal', '0.1', NULL, '2026-07-27', 'Restricted legacy archive aggregate index', 'local-vault://capabilities/switching-equipment', '141 indexed text hits; full files require local archive authorization and qualification.', 'capability-switching-141-20260721', NULL, 'AGT-009', 'Preserve until an approved retention rule exists.', '["switching","network equipment","historical capability"]', '["switches","routers","telecom equipment"]', 0, 0, '2026-07-21T11:40:00.000Z'),
	('SYM-ARC-RES-105', 'Historical capability — access control and security systems', 'Sanitized aggregate references for access control, surveillance, cameras, and physical-security systems; project-level evidence remains unqualified.', 'Archive', 'RES', 'AGT-005', 'AGT-005', 'Authorized executive', NULL, 'Review', 'Internal', '0.1', NULL, '2026-07-27', 'Restricted legacy archive aggregate index', 'local-vault://capabilities/security-systems', '87 combined indexed text hits; full files require local archive authorization and qualification.', 'capability-security-87-20260721', NULL, 'AGT-009', 'Preserve until an approved retention rule exists.', '["access control","security cameras","surveillance","historical capability"]', '["CCTV","physical security","ALPR"]', 0, 0, '2026-07-21T11:40:00.000Z'),
	('SYM-ARC-RES-106', 'Historical capability — IT consulting and program support', 'Sanitized aggregate evidence for technical proposals, requirements, qualifications, program management, implementation, and IT consulting support.', 'Archive', 'RES', 'AGT-005', 'AGT-005', 'Authorized executive', NULL, 'Review', 'Internal', '0.1', NULL, '2026-07-27', 'Restricted legacy archive aggregate index', 'local-vault://capabilities/it-consulting', '80 indexed text hits; full files require local archive authorization and qualification.', 'capability-it-consulting-80-20260721', NULL, 'AGT-009', 'Preserve until an approved retention rule exists.', '["IT consulting","program management","technical services","historical capability"]', '["implementation support","staff augmentation","technical proposal"]', 0, 0, '2026-07-21T11:40:00.000Z'),
	('SYM-RES-RES-201', 'New prerogative — 3D scanning and reality capture', 'Current company direction for 3D scanning, laser scanning, point clouds, reality capture, existing-condition documentation, BIM, and digital twins.', 'Research', 'RES', 'AGT-001', 'AGT-001', 'AGT-005', NULL, 'Review', 'Internal', '0.1', NULL, '2026-08-15', 'Symbiont operating charter', 'knowledge://company-prerogatives/3d-reality-capture', 'No verified historical project evidence was found in the archive; treat as a new prerogative until delivery evidence is approved.', 'prerogative-3d-reality-capture-20260721', NULL, 'AGT-009', 'Review quarterly with the company strategy.', '["3D scanning","laser scanning","reality capture","BIM","digital twin"]', '["point cloud","existing conditions","survey"]', 0, 0, '2026-07-21T11:40:00.000Z'),
	('SYM-RES-RES-202', 'New prerogative — building data and AI operations', 'Current company direction connecting physical buildings, reality capture, BIM, digital twins, IoT, structured building data, AI, and operational decisions.', 'Research', 'RES', 'AGT-001', 'AGT-001', 'AGT-005', NULL, 'Review', 'Internal', '0.1', NULL, '2026-08-15', 'Symbiont operating charter', 'knowledge://company-prerogatives/building-data-ai', 'Company value-chain directive; opportunity-specific claims still require evidence.', 'prerogative-building-data-ai-20260721', NULL, 'AGT-009', 'Review quarterly with the company strategy.', '["building data","AI","IoT","digital twin","facilities intelligence"]', '["asset information","operational decisions","building operating system"]', 0, 0, '2026-07-21T11:40:00.000Z')
ON CONFLICT(`id`) DO UPDATE SET
	`title` = excluded.`title`, `description` = excluded.`description`, `lifecycle_status` = excluded.`lifecycle_status`, `classification` = excluded.`classification`,
	`current_version` = excluded.`current_version`, `review_date` = excluded.`review_date`, `source_system` = excluded.`source_system`, `canonical_location` = excluded.`canonical_location`,
	`source_evidence` = excluded.`source_evidence`, `content_hash` = excluded.`content_hash`, `tags_json` = excluded.`tags_json`, `synonyms_json` = excluded.`synonyms_json`,
	`is_authoritative` = excluded.`is_authoritative`, `is_demonstration` = 0, `updated_at` = excluded.`updated_at`;
