import {NextResponse} from "next/server";
import {Document,HeadingLevel,Packer,Paragraph,TextRun} from "docx";
import {PDFDocument,StandardFonts,rgb} from "pdf-lib";
import {cleanResponseDraft,type ResponseDraft} from "@/lib/workflow-portal";

const sections:(keyof ResponseDraft)[]=["executiveSummary","understanding","approach","deliverables","schedule","team","assumptions","exclusions","pricing"];
const labels:Record<string,string>={executiveSummary:"Executive Summary",understanding:"Understanding of Requirements",approach:"Technical Approach",deliverables:"Deliverables",schedule:"Schedule",team:"Team",assumptions:"Assumptions",exclusions:"Exclusions",pricing:"Pricing"};
const safeName=(value:string)=>value.replace(/[^a-z0-9_-]+/gi,"-").replace(/^-|-$/g,"").slice(0,80)||"response";

export async function POST(request:Request){
 try{const draft=cleanResponseDraft(await request.json());const format=new URL(request.url).searchParams.get("format");
  if(format==="docx"){const children=[new Paragraph({children:[new TextRun({text:"DRAFT · HUMAN APPROVAL REQUIRED",bold:true})]}),new Paragraph({text:draft.title,heading:HeadingLevel.TITLE}),new Paragraph({children:[new TextRun({text:`${draft.responseType} response · ${draft.solicitation}`,bold:true}),new TextRun(`\nPrepared for ${draft.client}${draft.dueDate?` · Due ${draft.dueDate}`:""}`)]})];for(const key of sections){children.push(new Paragraph({text:labels[key],heading:HeadingLevel.HEADING_1}),...paragraphs(draft[key]));}children.push(new Paragraph({text:`Offer validity: ${draft.validity||"Not stated"}`}),new Paragraph({text:"This draft is not an external commitment. Pricing, contractual terms, scope, schedule, claims, and submission require authorized human approval."}));const doc=new Document({creator:"Symbiont OS",title:draft.title,description:`Draft ${draft.responseType} response`,sections:[{children}]});const buffer=await Packer.toBuffer(doc);const body=new Uint8Array(buffer);return new Response(body.buffer,{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","Content-Disposition":`attachment; filename="${safeName(draft.solicitation)}.docx"`}})}
  if(format==="pdf"){const pdf=await PDFDocument.create();const regular=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page=pdf.addPage([612,792]);let y=748;const write=(text:string,size=10,isBold=false)=>{for(const line of wrap(text,size,isBold?bold:regular,82)){if(y<54){page=pdf.addPage([612,792]);y=748;}page.drawText(line,{x:54,y,size,font:isBold?bold:regular,color:rgb(.08,.12,.1)});y-=size+5;}};write("DRAFT · HUMAN APPROVAL REQUIRED",9,true);y-=8;write(draft.title,20,true);write(`${draft.responseType} response · ${draft.solicitation}`,11,true);write(`Prepared for ${draft.client}${draft.dueDate?` · Due ${draft.dueDate}`:""}`,10);y-=12;for(const key of sections){write(labels[key],13,true);write(draft[key]||"Not provided.",10);y-=9;}write(`Offer validity: ${draft.validity||"Not stated"}`,10,true);write("This draft is not an external commitment. Pricing, contractual terms, scope, schedule, claims, and submission require authorized human approval.",8);const bytes=await pdf.save();const body=new Uint8Array(bytes);return new Response(body.buffer,{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="${safeName(draft.solicitation)}.pdf"`}})}
  return NextResponse.json({error:"Use format=docx or format=pdf."},{status:400});
 }catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to create export."},{status:400})}}
function paragraphs(value:string){return (value||"Not provided.").split(/\n+/).map(text=>new Paragraph({text:text.trim()||" "}));}
function wrap(text:string,size:number,font:{widthOfTextAtSize:(text:string,size:number)=>number},maxChars:number){const output:string[]=[];for(const raw of (text||"Not provided.").split(/\n/)){let line="";for(const word of raw.split(/\s+/)){const next=line?`${line} ${word}`:word;if(next.length>maxChars||font.widthOfTextAtSize(next,size)>500){if(line)output.push(line);line=word}else line=next}output.push(line||" ")}return output;}
