import test from "node:test";
import assert from "node:assert/strict";
import {assertDraftAuthority,assertEconomicsInputs,assertLifecycleTransition,assertProposalVersion,draftProductClaim,qualifyConcept} from "../../lib/product-architecture.ts";

test("qualification requires all fourteen evidence-backed dimensions",()=>{const result=qualifyConcept({problemSeverity:5,buyerClarity:4});assert.equal(result.classification,"Explore");assert.equal(result.missing.length,12);});
test("qualification produces a bounded recommendation",()=>{const scores={problemSeverity:5,buyerClarity:4,frequency:4,strategicFit:5,repeatability:4,technicalFeasibility:4,deliveryFeasibility:4,dataAvailability:4,qualityRisk:4,securityRisk:4,marginPotential:4,recurringRevenuePotential:5,differentiation:4,evidenceStrength:4};assert.equal(qualifyConcept(scores).classification,"Productize");});
test("L1 authority refuses commercial and external commitments",()=>{assert.throws(()=>assertDraftAuthority("Approve pricing for the client"),/L1 Draft/);assert.equal(assertDraftAuthority("Draft a product brief"),true);});
test("lifecycle cannot skip stages or promote without evidence",()=>{assert.throws(()=>assertLifecycleTransition("Discovery","Pilot",{}),/one stage/);assert.throws(()=>assertLifecycleTransition("Validation","Pilot",{approval:true}),/boundedScope/);assert.equal(assertLifecycleTransition("Validation","Pilot",{approval:true,boundedScope:true,acceptance:true,qualityPlan:true,securityPlan:true,economicsInputs:true}),true);});
test("proposal use is limited to approved current product versions",()=>{assert.throws(()=>assertProposalVersion({approvalStatus:"Approved",proposalEligible:true},"VER-2","VER-1"),/approved, current/);assert.throws(()=>assertProposalVersion({approvalStatus:"Draft",proposalEligible:true},"VER-2","VER-2"),/approved, current/);assert.equal(assertProposalVersion({approvalStatus:"Approved",proposalEligible:true},"VER-2","VER-2"),true);});
test("economics requires all cost inputs",()=>{assert.throws(()=>assertEconomicsInputs({deliveryCost:10}),/softwareCost/);assert.equal(assertEconomicsInputs({deliveryCost:10,softwareCost:2,supportCost:3,implementationCost:4,contingencyCost:1}),true);});
test("unsupported product claims are refused",()=>{assert.throws(()=>draftProductClaim("Cuts operating cost 30%",{source:"one anecdote"}),/Unsupported product claim refused/);assert.match(draftProductClaim("Reduced validation time 18%",{source:"PIL-004",baseline:"24 hours",method:"before/after",observed:true}),/PIL-004/);});
