import assert from "node:assert/strict";import test from "node:test";
import {cleanResponseDraft,demonstrationPortalProjects,mergePortalProject,portalProjectFromOpportunity,stageActionLabel,validateStageMove,visiblePortalProjects} from "../../lib/workflow-portal.ts";
test("workflow advances only one governed stage",()=>{assert.equal(validateStageMove("intake","qualification",true),true);assert.throws(()=>validateStageMove("intake","response",true),/one governed stage/);assert.throws(()=>validateStageMove("intake","qualification",false),/gate/)});
test("workflow actions describe the governed handoff",()=>{assert.equal(stageActionLabel("intake"),"Accept and send to Sales Qualification");assert.equal(stageActionLabel("closeout"),"Approve closeout and archive")});
test("action records preserve recommendations, approvals, provenance, and activity",()=>{for(const project of demonstrationPortalProjects){assert.ok(project.recommendation);assert.ok(project.rationale);assert.ok(project.source);assert.ok(project.activities.length);assert.ok(project.confidence>=0&&project.confidence<=100);assert.ok(project.completedApprovals.every(approval=>project.approvals.includes(approval)))}});
test("pipeline handoff creates one governed action record with preserved provenance",()=>{const record=portalProjectFromOpportunity({id:"OPP-LIVE-1",title:"Live RFQ",client:"Public owner",solicitation:"RFQ-42",stage:"Qualified",nextAction:"Record bid decision",dueDate:"2026-08-01",recommendation:"Review",confidence:87,source:"Governed pipeline",sourceUpdatedAt:"2026-07-21T16:00:00Z",canonicalUrl:"https://example.gov/rfq-42",isDemonstration:false});assert.equal(record.stage,"qualification");assert.equal(record.owner,"AGT-002");assert.equal(record.client,"Public owner");assert.equal(record.isDemonstration,false);assert.match(record.activities[0].evidence||"",/example\.gov/);assert.equal(mergePortalProject([record],record).length,1)});
test("live Action queue excludes every demonstration record",()=>{const live=portalProjectFromOpportunity({id:"OPP-LIVE-2",title:"Live opportunity",stage:"Lead",isDemonstration:false});const combined=[...demonstrationPortalProjects,live];assert.deepEqual(visiblePortalProjects(combined,false).map(item=>item.id),["OPP-LIVE-2"]);assert.equal(visiblePortalProjects(combined,true).length,demonstrationPortalProjects.length)});
test("response exports require identifying fields",()=>assert.throws(()=>cleanResponseDraft({responseType:"RFP"}),/Client/));
test("response draft is normalized and bounded",()=>{const value=cleanResponseDraft({responseType:"RFQ",client:" Agency ",title:" Work ",solicitation:" RFQ-1 ",approach:"x".repeat(13000)});assert.equal(value.responseType,"RFQ");assert.equal(value.client,"Agency");assert.equal(value.approach.length,12000)});
