"use client";
import type { FinanceData, FinanceMetric } from "@/lib/finance";

export function FinanceControl({data}:{data:FinanceData|null}){
 if(!data)return <section className="finance-view"><Hero/><div className="finance-loading">FINANCE EVIDENCE ADAPTER · CHECKING</div></section>;
 const live=data.source==="d1", get=(name:string)=>data.metrics.find(m=>m.name===name), revenue=get("Revenue actual"),plan=get("Revenue plan"),conc=get("Revenue concentration");
 return <section className="finance-view"><Hero/><div className={`finance-disclosure ${live?"live":"demo"}`}><div><i className={`dot ${live?"green":"amber"}`}/><b>{live?"AUTHENTICATED D1 METADATA":"DEMONSTRATION DATA"}</b></div><p>{data.activation}</p><span>AS OF {dt(data.asOf)}</span></div>
 <div className="finance-metrics"><Metric metric={revenue} plan={plan}/>{["Gross profit","Gross margin","Cash balance","DSO","Utilization","Contracted backlog","Recurring revenue"].map(n=><Metric key={n} metric={get(n)}/>)}</div>
 <div className="finance-grid primary"><section className="finance-panel"><Title kicker="Project financial control" title="Margin health" suffix={`${data.projects.length} projects`}/><div className="finance-table-head"><span>Project</span><span>Contract / billed</span><span>Labor + direct cost</span><span>Margin</span></div>{data.projects.map(p=><article className="finance-project" key={p.id}><div><p>{p.id}</p><h4>{p.client}</h4><small>{p.confidence} confidence</small></div><div><b>{money(p.contractValue+p.approvedChanges)}</b><small>{money(p.invoiced)} invoiced · {money(p.collected)} collected</small></div><div><b>{money(p.actualLabor+p.directCost)}</b><small>{money(p.remainingEffort)} remaining effort</small></div><div><span className={`finance-health ${p.health.toLowerCase()}`}>{p.health}</span><b>{p.currentMargin.toFixed(1)}%</b><small>{signed(p.marginVariance)} pts vs baseline</small></div>{p.risks.map(r=><p className="finance-risk" key={r}>{r}</p>)}</article>)}</section>
 <aside className="finance-panel cash-panel"><Title kicker="Cash forecast" title="Scenario range" suffix="No false precision"/>{data.cashScenarios.map(s=><article key={s.name}><div><b>{s.name}</b><span className={`confidence ${s.confidence.toLowerCase()}`}>{s.confidence}</span></div><strong>{s.closingCash===null?"—":money(s.closingCash)}</strong><p>Runway {s.runwayMonths===null?"insufficient inputs":`${s.runwayMonths.toFixed(1)} months`}</p><small>{s.assumptions.join(" · ")}</small><em>{s.exclusions.join(" · ")}</em></article>)}</aside></div>
 <div className="finance-grid secondary"><section className="finance-panel"><Title kicker="Accounts receivable" title="Aging and action control" suffix={`${data.receivables.filter(r=>r.daysOutstanding>30).length} aged`}/>{data.receivables.map(r=><article className="receivable-row" key={r.id}><div><p>{r.id} · {r.projectId}</p><h4>{r.client}</h4><small>Due {date(r.dueDate)} · {r.daysOutstanding} days outstanding</small></div><div><b>{money(r.balance)}</b><small>of {money(r.amount)}</small></div><div><span className={r.daysOutstanding>45?"red-text":r.daysOutstanding>30?"amber-text":""}>{r.daysOutstanding>45?"ESCALATE":r.daysOutstanding>30?"REVIEW":"CURRENT"}</span><small>{r.owner??"MISSING OWNER"}</small><small>{r.nextAction??"MISSING NEXT ACTION"}</small></div></article>)}</section>
 <section className="finance-panel"><Title kicker="Invoice readiness" title="Draft gate" suffix="Issuance requires approval"/>{data.invoiceReadiness.map(i=><article className="invoice-row" key={i.id}><div><p>{i.id} · {i.projectId}</p><h4>{i.status}</h4><small>{i.missing.length?i.missing.join(" · "):"Evidence checklist complete"}</small></div><div><b>{money(i.remainingContractBalance)}</b><small>Remaining contract</small><small>Owner · {i.approvalOwner}</small></div></article>)}</section></div>
 <div className="finance-grid tertiary"><section className="finance-panel"><Title kicker="Risk signals" title="Exceptions + concentration" suffix={`${data.exceptions.length} open`}/><div className="finance-concentration"><div><span>Largest client share</span><strong>{val(conc)}</strong><small>{conc?.confidence??"Insufficient"} confidence</small></div><div><span>Last reconciliation</span><strong>{data.lastReconciliation?date(data.lastReconciliation):"NOT COMPLETE"}</strong><small>{data.authoritativeSystem}</small></div></div>{data.exceptions.map(e=><article className="finance-exception" key={e.id}><span className={e.severity.toLowerCase()}>{e.severity}</span><div><p>{e.id} · {e.source}</p><h4>{e.title}</h4><small>{e.requiredAction} · Owner: {e.owner}</small></div></article>)}</section>
 <section className="finance-panel"><Title kicker="Vendor control" title="Renewal horizon" suffix={`${data.renewals.length} visible`}/>{data.renewals.map(r=><article className="renewal-row" key={`${r.vendor}-${r.service}`}><div><p>{r.vendor}</p><h4>{r.service}</h4><small>{r.owner??"MISSING OWNER"}</small></div><div><b>{date(r.renewalDate)}</b><small>{money(r.annualCost)} annual</small><span>{r.status}</span></div></article>)}</section></div>
 <details className="finance-definitions"><summary>Metric definitions, sources, owners, refresh times, confidence, and reconciliation</summary><div>{data.metrics.map(m=><article key={m.name}><h4>{m.name}</h4><p>{m.definition}</p><dl><div><dt>Category / period</dt><dd>{m.category} · {m.period}</dd></div><div><dt>Source</dt><dd>{m.sourceSystem} · {m.sourceRecord}</dd></div><div><dt>Owner / refresh</dt><dd>{m.owner} · {dt(m.refreshedAt)}</dd></div><div><dt>Confidence</dt><dd>{m.confidence}</dd></div><div><dt>Reconciliation</dt><dd>{m.reconciliationStatus}</dd></div><div><dt>Method</dt><dd>{m.calculation}</dd></div></dl></article>)}</div></details>
 <div className="authority-strip"><div><span>AGT-006</span><strong>L1 · DRAFT FINANCIAL CONTROL</strong></div><p>May reconcile approved data, calculate labeled metrics, forecast scenarios, identify exceptions, and prepare draft invoice packages. It cannot move money, issue invoices, alter the accounting ledger, approve expenses, set tax treatment, or make commitments.</p><b>APPROVED ACCOUNTING PLATFORM REMAINS AUTHORITATIVE</b></div></section>
}
function Hero(){return <div className="finance-hero"><div><p className="eyebrow">AGT-006 · Finance Operations</p><h2>See the cash.<br/><em>Protect the margin.</em></h2></div><p>Reconciled operational finance, invoice readiness, receivables, project margin, and scenario forecasts—without replacing the accounting ledger or crossing approval boundaries.</p></div>}
function Metric({metric,plan}:{metric?:FinanceMetric;plan?:FinanceMetric}){const variance=metric?.value!=null&&plan?.value!=null?metric.value-plan.value:null;return <article><span>{metric?.name??"Unavailable"}</span><strong>{val(metric)}</strong><p>{variance===null?metric?.category??"Missing data":`${signed(variance)} vs plan`}</p><small>{metric?.confidence??"Insufficient"} · {metric?.period??"No period"}</small></article>}
function Title({kicker,title,suffix}:{kicker:string;title:string;suffix:string}){return <div className="finance-panel-title"><div><p>{kicker}</p><h3>{title}</h3></div><span>{suffix}</span></div>}
function val(m?:FinanceMetric){if(!m||m.value===null)return"—";return m.unit==="USD"?money(m.value):m.unit==="%"?`${m.value.toFixed(1)}%`:`${m.value.toFixed(0)} ${m.unit}`}
function money(n:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:Math.abs(n)>=1000000?"compact":"standard",maximumFractionDigits:0}).format(n)}
function signed(n:number){return `${n>=0?"+":""}${new Intl.NumberFormat("en-US",{maximumFractionDigits:1}).format(n)}`}
function date(v:string){const d=new Date(v);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(d):v}
function dt(v:string){const d=new Date(v);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(d):v}
