"use client";
import type { ProductPortfolioData } from "@/lib/product-architecture";
export function ProductControl({data}:{data:ProductPortfolioData|null}){if(!data)return <section className="product-view"><div className="product-loading">AGT-010 · CHECKING PRODUCT EVIDENCE</div></section>;const activePilots=data.products.filter(p=>p.stage==="Pilot").length;const recurring=data.products.filter(p=>p.recurring==="High").length;const unresolved=data.products.reduce((sum,p)=>sum+p.assumptions,0);const modules=data.products.reduce((sum,p)=>sum+p.modules,0);return <section className="product-view">
<div className="product-hero"><div><p className="eyebrow">AGT-010 · Product &amp; Service Architecture</p><h2>Configured products.<br/><em>Measured outcomes.</em></h2></div><p>Turn recurring delivery knowledge into bounded building-intelligence products—from reality capture and BIM through digital twins, IoT, building data, and AI-enabled decisions.</p></div>
<div className={`product-disclosure ${data.source==="d1"?"live":""}`}><b>{data.source==="d1"?"LIVE D1 EVIDENCE":"DEMONSTRATION DATA"}</b><span>{data.activation}</span><i>L1 · DRAFT</i></div>
<div className="product-metrics"><Metric label="Portfolio" value={data.products.length} note="Controlled definitions"/><Metric label="Active pilots" value={activePilots} note="Bounded validation"/><Metric label="High recurring" value={recurring} note="Potential, not forecast"/><Metric label="Reusable modules" value={modules} note="Versioned capabilities"/><Metric label="Assumptions" value={unresolved} note="Unresolved" tone="amber"/><Metric label="Retirement" value={data.products.filter(p=>p.retirementCandidate).length} note="Candidates" tone="red"/></div>
<div className="product-grid primary"><div className="product-panel"><Title kicker="Portfolio" title="Product health + lifecycle" aside={`${data.products.length} definitions`}/><div className="product-head"><span>Product / version</span><span>Lifecycle + health</span><span>Economics</span><span>Delivery evidence</span></div>{data.products.map(p=><article className="product-row" key={p.id}><div><p>{p.id} · v{p.version}</p><h3>{p.name}</h3><small>{p.feedback}</small></div><div><b className={`product-stage ${p.stage.toLowerCase()}`}>{p.stage}</b><small>{p.health} health · {p.pilot}</small><span>{p.proposalEligible?"Proposal eligible":"Proposal use blocked"}</span></div><div><b>{p.recurring} recurring</b><small>Margin {p.margin==null?"Evidence missing":`${p.margin}% forecast`}</small><span>Adoption {p.adoption==null?"—":`${p.adoption}%`}</span></div><div><b>{p.modules} modules · {p.quality} findings</b><small>Variation {p.variation==null?"—":`${p.variation}%`}</small><span className={p.assumptions?"amber-text":""}>{p.assumptions} unresolved assumptions</span></div></article>)}</div>
<div className="product-panel product-gates"><Title kicker="Lifecycle control" title="Evidence before promotion" aside="No stage skipping"/><ol><li><b>VALIDATE</b><span>Baseline + falsifiable assumptions</span></li><li><b>PILOT</b><span>Approval + bounded acceptance</span></li><li><b>ACTIVE</b><span>Outcome + effort + defects + economics</span></li><li><b>SCALE</b><span>Multi-client evidence + capacity</span></li></ol></div></div>
<div className="product-grid secondary"><div className="product-panel"><Title kicker="Roadmap" title="Commitments separated from candidates" aside={`${data.roadmap.length} items`}/>{data.roadmap.map(item=><article className="roadmap-row" key={item.id}><b>{item.lane}</b><div><p>{item.id} · {item.productId}</p><h4>{item.title}</h4></div><span>{item.status}<small>{item.targetDate??"No approved date"}</small></span></article>)}</div><div className="product-panel retirement"><Title kicker="Portfolio decisions" title="Retirement candidates" aside="Approval required"/>{data.products.filter(p=>p.retirementCandidate).map(p=><article key={p.id}><b>{p.id}</b><h4>{p.name}</h4><p>{p.feedback}</p><span>Impact + successor analysis required</span></article>)}{!data.products.some(p=>p.retirementCandidate)&&<p className="product-empty">No evidence-backed candidates.</p>}</div></div>
<div className="product-authority"><div><b>AGT-002 / 003 / 004 / 013</b><span>Demand, delivery, quality, client evidence</span></div><i>→</i><div><b>AGT-010</b><span>Definition, modules, lifecycle recommendation</span></div><i>→</i><div><b>AGT-006 + HUMAN</b><span>Economics review + approvals</span></div></div></section>}
function Metric({label,value,note,tone=""}:{label:string;value:number;note:string;tone?:string}){return <article><span>{label}</span><strong className={tone}>{String(value).padStart(2,"0")}</strong><p>{note}</p></article>}
function Title({kicker,title,aside}:{kicker:string;title:string;aside:string}){return <header className="product-title"><div><p>{kicker}</p><h3>{title}</h3></div><span>{aside}</span></header>}
