"use client";
import {useMemo,useState} from "react";
import {demonstrationPortalProjects,WORKFLOW_STAGES,type PortalProject,type ResponseDraft,type WorkflowStageId} from "@/lib/workflow-portal";

const blank:ResponseDraft={responseType:"RFP",solicitation:"",client:"",title:"",dueDate:"",executiveSummary:"",understanding:"",approach:"",deliverables:"",schedule:"",team:"",assumptions:"",exclusions:"",pricing:"",validity:"30 days"};

export function WorkflowPortal({accessKey}:{accessKey:string}){
 const [projects,setProjects]=useState<PortalProject[]>(demonstrationPortalProjects); const [selectedId,setSelectedId]=useState(projects[0].id);
 const [draft,setDraft]=useState<ResponseDraft>(blank); const [gate,setGate]=useState(false); const [notice,setNotice]=useState(""); const [tab,setTab]=useState<"actions"|"response">("actions");
 const selected=useMemo(()=>projects.find(p=>p.id===selectedId)!,[projects,selectedId]); const stageIndex=WORKFLOW_STAGES.findIndex(s=>s.id===selected.stage);
 function updateProject(patch:Partial<PortalProject>){setProjects(items=>items.map(item=>item.id===selectedId?{...item,...patch}:item));}
 async function advance(){setNotice("");const next=WORKFLOW_STAGES[stageIndex+1];if(!next)return setNotice("This project is already at closeout.");if(!gate)return setNotice("Confirm the stage gate before advancing.");updateProject({stage:next.id,owner:next.agent,progress:Math.round((stageIndex+2)/WORKFLOW_STAGES.length*100)});setGate(false);setNotice(`Advanced to ${next.label}. Save to the governed data plane before treating this as authoritative.`)}
 async function syncNotion(){setNotice("Syncing…");const r=await fetch("/api/workflow/notion",{method:"POST",headers:{"Content-Type":"application/json",...(accessKey?{"x-symbiont-access-key":accessKey}:{})},body:JSON.stringify(selected)});const result=await r.json();if(r.ok&&result.url)updateProject({notionUrl:result.url});setNotice(result.message||result.error||"Notion sync finished.");}
 async function exportFile(format:"docx"|"pdf"){setNotice("Preparing export…");const r=await fetch(`/api/responses/export?format=${format}`,{method:"POST",headers:{"Content-Type":"application/json",...(accessKey?{"x-symbiont-access-key":accessKey}:{})},body:JSON.stringify(draft)});if(!r.ok){const e=await r.json();return setNotice(e.error||"Export failed safely.");}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${draft.solicitation||"response"}.${format}`;a.click();URL.revokeObjectURL(url);setNotice(`${format.toUpperCase()} export created. External issue still requires human approval.`)}
 return <section className="workflow-view">
  <div className="workflow-hero"><div><p className="eyebrow">Symbiont action portal</p><h2>Opportunity to <em>delivery.</em></h2></div><p>Move work through one controlled operating path. Each transition requires evidence, a named owner, and an explicit gate.</p></div>
  <div className="workflow-tabs"><button className={tab==="actions"?"active":""} onClick={()=>setTab("actions")}>Project actions</button><button className={tab==="response"?"active":""} onClick={()=>setTab("response")}>RFP / RFQ response studio</button><span>L1 draft · approval required for external issue</span></div>
  {notice&&<div className="workflow-notice" role="status">{notice}</div>}
  {tab==="actions"?<>
   <div className="stage-rail">{WORKFLOW_STAGES.map((stage,i)=><button key={stage.id} className={i<stageIndex?"done":i===stageIndex?"current":""} title={stage.gate}><b>{String(i+1).padStart(2,"0")}</b><span>{stage.label}</span><small>{stage.agent}</small></button>)}</div>
   <div className="workflow-grid"><aside className="work-list"><header><p className="eyebrow">Active work</p><button onClick={()=>{const id=`OPP-${new Date().getFullYear()}-${String(projects.length+22).padStart(3,"0")}`;setProjects(v=>[{id,title:"New opportunity",client:"",solicitation:"",stage:"intake",owner:"AGT-009",dueDate:"",nextAction:"Complete opportunity intake",progress:5,approvals:[]},...v]);setSelectedId(id)}}>+ New</button></header>{projects.map(p=><button key={p.id} className={p.id===selectedId?"selected":""} onClick={()=>{setSelectedId(p.id);setGate(false);setNotice("")}}><small>{p.id} · {WORKFLOW_STAGES.find(s=>s.id===p.stage)?.label}</small><strong>{p.title}</strong><span>{p.client||"Client required"}</span><i style={{width:`${p.progress}%`}}/></button>)}</aside>
   <div className="work-editor"><header><div><p className="eyebrow">{selected.id} · {selected.owner}</p><h3>{selected.title}</h3></div><span>{selected.progress}% complete</span></header><div className="field-grid"><Field label="Project / opportunity title" value={selected.title} onChange={v=>updateProject({title:v})}/><Field label="Client / issuer" value={selected.client} onChange={v=>updateProject({client:v})}/><Field label="Solicitation / agreement" value={selected.solicitation} onChange={v=>updateProject({solicitation:v})}/><Field label="Current owner" value={selected.owner} onChange={v=>updateProject({owner:v})}/><Field label="Due date" value={selected.dueDate} type="date" onChange={v=>updateProject({dueDate:v})}/><Field label="Next action" value={selected.nextAction} onChange={v=>updateProject({nextAction:v})}/><Field label="Notion page URL" value={selected.notionUrl||""} onChange={v=>updateProject({notionUrl:v})}/></div><div className="gate-card"><div><p className="eyebrow">Current release gate</p><strong>{WORKFLOW_STAGES[stageIndex].gate}</strong><small>Evidence must be stored in an approved system of record.</small></div><label><input type="checkbox" checked={gate} onChange={e=>setGate(e.target.checked)}/> I confirm this gate is satisfied</label></div><div className="editor-actions"><button className="secondary" onClick={syncNotion}>↗ Sync / link Notion</button>{selected.notionUrl&&<a href={selected.notionUrl} target="_blank" rel="noreferrer">Open Notion</a>}<button className="primary" onClick={advance}>Advance to next stage →</button></div></div></div>
  </>:<ResponseStudio draft={draft} setDraft={setDraft} exportFile={exportFile}/>}</section>
}

function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="portal-field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Area({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="portal-area"><span>{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function ResponseStudio({draft,setDraft,exportFile}:{draft:ResponseDraft;setDraft:(v:ResponseDraft)=>void;exportFile:(f:"docx"|"pdf")=>void}){const change=(key:keyof ResponseDraft,value:string)=>setDraft({...draft,[key]:value});return <div className="response-studio"><aside><p className="eyebrow">Response controls</p><label className="portal-field"><span>Response type</span><select value={draft.responseType} onChange={e=>change("responseType",e.target.value)}><option>RFP</option><option>RFQ</option></select></label><Field label="Solicitation number" value={draft.solicitation} onChange={v=>change("solicitation",v)}/><Field label="Client / agency" value={draft.client} onChange={v=>change("client",v)}/><Field label="Response title" value={draft.title} onChange={v=>change("title",v)}/><Field label="Due date" value={draft.dueDate} type="date" onChange={v=>change("dueDate",v)}/><Field label="Offer validity" value={draft.validity} onChange={v=>change("validity",v)}/><div className="export-stack"><button onClick={()=>exportFile("docx")}>Export Word</button><button onClick={()=>exportFile("pdf")}>Export PDF</button></div><small className="approval-note">Exports are marked Draft. Pricing and external submission require authorized human approval.</small></aside><div className="response-form"><header><div><p className="eyebrow">Draft response document</p><h3>{draft.title||"Untitled response"}</h3></div><span>{draft.responseType}</span></header><Area label="Executive summary" value={draft.executiveSummary} onChange={v=>change("executiveSummary",v)} placeholder="Why Symbiont, the desired client outcome, and the bounded offer…"/><Area label="Understanding of requirements" value={draft.understanding} onChange={v=>change("understanding",v)} placeholder="Verified needs, constraints, acceptance criteria, and missing information…"/><Area label="Technical approach" value={draft.approach} onChange={v=>change("approach",v)} placeholder="Methods, tools, controls, handoffs, and quality gates…"/><Area label="Deliverables" value={draft.deliverables} onChange={v=>change("deliverables",v)} placeholder="One deliverable per line with format and acceptance basis…"/><div className="area-pair"><Area label="Schedule" value={draft.schedule} onChange={v=>change("schedule",v)} placeholder="Milestones and dependencies…"/><Area label="Team" value={draft.team} onChange={v=>change("team",v)} placeholder="Roles, qualifications, and responsibilities…"/></div><div className="area-pair"><Area label="Assumptions" value={draft.assumptions} onChange={v=>change("assumptions",v)} placeholder="One assumption per line…"/><Area label="Exclusions" value={draft.exclusions} onChange={v=>change("exclusions",v)} placeholder="Licensed, hazardous, concealed, or client-owned scope…"/></div><Area label="Pricing architecture" value={draft.pricing} onChange={v=>change("pricing",v)} placeholder="Human-approved commercial structure or 'Pricing submitted separately'…"/></div></div>}
